language: ruby
cache: bundler
sudo: false
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9
  exclude:
    - rvm: 2.0
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.1
      gemfile: gemfiles/Gemfile.rails-4.2.x
  include:
    - rvm: 1.9
      gemfile: gemfiles/Gemfile.rails-3.0.x
    - rvm: 1.9
      gemfile: gemfiles/Gemfile.rails-3.1.x
