language: ruby
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.1.7
      gemfile: gemfiles/Gemfile.rails-4.2.x
matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-3.0.x
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-3.1.x
