language: ruby
cache: bundler
sudo: false
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - ruby-head
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9.3
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.1.7
      gemfile: gemfiles/Gemfile.rails-4.2.x
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-3.0.x
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-3.1.x
